apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: metallb
  namespace: flux-system
spec:
  interval: 1m
  path: "./clusters/my-cluster/infrastructure/metallb"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: metallb-system
