apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: infrastructure
spec:
  interval: 1m
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: "./clusters/my-cluster/infrastructure"
  targetNamespace: flux-system
  resources:
    - ./metallb

